cluster:
  n_clusters: 2
  max_iter: 1000
  algorithm: auto
  random_state: 42

train_test_split:
  test_size: 0.2
  random_state: 42

classifier:
  layers:
    first:
      neurons: 8
      activation: relu
    second:
      neurons: 8
      activation: relu
    output:
      neurons: 1
      activation: sigmoid
  loss: binary_crossentropy
  optimizer: adam
  metrics: accuracy
  epochs: 20
  batch_size: 100
  validation_split: 0.2
  verbose: 0
